config/routes.rb
Mystore::Application.routes.draw do
  resources :users
  resources :stores
  resources :items
  resources :assets
  
  root :to => "stores#home"

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match '/admin' => 'admins#index', :as => :admin_index

  match '/admin/active' => 'admins#active', :as => :active

  match '/admin/inactive' => 'admins#inactive', :as => :inactive

  match 'show-item' => "stores#show_item" , :as => :show_item
  
  match 'show-store-item' => "stores#show_store_item" , :as => :show_store_item

  match 'add_to_cart' =>'stores#add_to_cart' , :as => :add_to_cart

  match 'show-cart' => 'stores#show_cart' , :as => :show_cart

  match 'remove-item/:id' =>'stores#remove_cart' , :as => :remove_cart

  match 'empty-cart' =>'stores#empty_cart' , :as => :empty_cart

  match 'update-cart' => 'stores#update_cart' , :as => :update_cart

  match 'new-address' =>'stores#new_address' , :as => :new_address

  match 'paypal'   =>'stores#paypal' ,:as => :paypal

  match 'indexpaypal'   =>'stores#indexpaypal' ,:as => :indexpaypal

  match 'payment-status' => 'stores#payment_status' , :as => :payment_status

  match 'payment-success' => 'stores#payment_success' , :as => :payment_success

  match 'payment-error' => 'stores#payment_error' , :as => :payment_error

  match 'all-charity' => 'stores#all_charity' , :as => :all_charity

  match 'all-club' => 'stores#all_club' , :as => :all_club

end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :user
  has_many :assets, :as => :attachable, :dependent => :destroy
  Max_Attachments = 1
	#validate :validate_attachments
 has_attached_file :avatar,:styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  
  def index
    @stores=Store.all
  end

  def home
    @items=Item.all
  end

  def show_item
    @item=Item.find(params[:id])
  end

  def show_store_item
    
    @items=Item.find(:all , :conditions => ["store_id =?", params[:id]])
    @store=Store.find(params[:id])
  end

  def add_to_cart
    item_hash = "item_#{params[:item_id]}".to_sym
    if session[:cart].blank?
      cart = []
      cart << params[item_hash]
      session[:cart] = cart
    else
      a = false
      session[:cart].each do |p|
        if p[:item_id] == params[:item_id]
          p[:quantity] = p[:quantity].to_i + params[item_hash][:quantity].to_i
          a = true
        end
      end
      if a == false
        session[:cart] << params[item_hash]
      end
    end
    redirect_to show_cart_path
  end

  def show_cart
    @cart = session[:cart]
    #    create_address if params[:order]
  end

  def remove_cart
    @cart = session[:cart]
    @cart.each do |p|
      if p[:item_id] == params[:id]
        p[:quantity]= nil
      end
    end
    redirect_to show_cart_path
  end

  def empty_cart
    session[:cart]=nil
    redirect_to root_path
  end

  def update_cart
    @cart = session[:cart]
    @cart.each do |p|
      if p[:item_id] == params[:cart][:id]
        p[:quantity]= params[:cart][:quantity]
      end
    end
    redirect_to show_cart_path
  end

  def new_address
    @order = Order.new
  end

  def paypal
    @order = Order.new(params[:order])
    @cart = session[:cart]
    $shipping = 0
    @cart.each do |cr|
      $shipping = $shipping.to_i + cr[:quantity].to_i
      item = Item.find_by_id(cr[:item_id])
      @order.price = $sum.to_f
      @order.net_price = @order.price.to_i
      @order.lineitems.build({:item_id=>cr[:item_id],:quantity=>cr[:quantity],:price=>item.price})
      
    end
    
    if @order.valid?
      @order.price = $sum.to_f
      @order.save
      redirect_to indexpaypal_path(:id => @order.id)
    else
      render :action => "new_address"
    end  

  end

  def indexpaypal
    session[:cart] = nil
    @order = Order.find(params[:id])
    @return_url = url_for(:controller => :stores, :action => :payment_status)
    @cancel_url = url_for(:controller => :stores, :action => :indexpaypal, :id => @order.id)
  end

  def payment_status
    #puts"payment DAte#{Time.parse(params[:payment_date]) }"
    if params[:payment_status] == "Completed"
      lineitem = Lineitem.find_by_item_no(params[:item_number1])
      lineitem.order.update_attributes(:transaction_id => params[:txn_id], :payment_at =>params[:payment_date] , :payment_status => true)
      redirect_to payment_success_path
    else
      redirect_to payment_error_path
    end
  end

  def all_charity
    # @charities=Store.find(:all , :conditions => ["store_type=?","charity"])
    @charities=Store.find_by_sql("Select * from stores,users where stores.user_id=users.id and users.status=1 and stores.store_type='charity'")
  end

  def all_club
    #    @clubs=Store.find(:all , :conditions => ["store_type=?","club"])
    @clubs=Store.find_by_sql("Select * from stores,users where stores.user_id=users.id and users.status=1 and stores.store_type='club'")
  end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_attachment.html.erb
<% if !attachment.id.nil? %><li id='attachment_<%=attachment.id %>'><a href='<%=attachment.url %>'><%=attachment.name %></a> (<%=attachment.file_size/1.kilobyte %>KB)
<%= link_to_remote "Remove", :url => asset_path(:id => attachment), :method => :delete, :html => { :title  => "Remove this attachment", :id => "remove" } %></li>
<% end %>

app/views/stores/all_charity.html.erb
<h2>Listing Charities</h2><br/>
<div class="FL" style="width:235px;"></div>
<div class="FL" style="width:765px;">
   <% @charities.each do |club| %>
  <div style="margin-left:20px;">
    <div class="FL list_text" style="width:150px;"><%= image_tag Store.find(:first, :conditions => ["user_id=?",club.user_id]).avatar.url(:thumb)  %></div>
    <div class="FL list_text" style="width:150px;"><%=  club.organizationname  %></div>
    <div class="FL list_text" style="width:150px;"><%= club.sport %></div>
    <div class="FL list_text" style="width:150px;"><%= club.state  %></div>
    <div class="clear"></div>
  </div>
  <% end %>
  
  <div>&nbsp;</div>
</div>
<div class="clear"></div>
<div>&nbsp;</div>

app/views/stores/all_club.html.erb
<h2>Listing Club</h2><br/>
<div class="FL" style="width:235px;"></div>
<div class="FL" style="width:765px;">
  <% @clubs.each do |club| %>
    <div style="margin-left:20px;">
      <div class="FL list_text" style="width:150px;"><%= image_tag Store.find(:first, :conditions => ["user_id=?",club.user_id]).avatar.url(:thumb) %></div>
      <div class="FL list_text" style="width:150px;"><%= club.organizationname %></div>
      <div class="FL list_text" style="width:150px;"><%= club.sport %></div>
      <div class="FL list_text" style="width:150px;"><%= club.state  %></div>
      <div class="clear"></div>
    </div>
  <% end %>
  <div>&nbsp;</div>

</div>
<div class="clear"></div>
<div>&nbsp;</div>

app/views/stores/home.html.erb
<div class="main_wrap">
  <div class="FL" style="width:235px;">Category</div>
  <div class="FL" style="width:765px;">
    <div style="margin-left:20px;">
      <div class="FL gd" style="width:300px;"><%= link_to "List Of All Charity" ,all_charity_path  %></div>
      <div class="FL gd"><%= link_to "List Of All Club" ,all_club_path  %></div>
      <div class="clear"></div>
    </div>
    <div>&nbsp;</div>
    <div class="listing">
      <ul>
        <%= temp_item="" %>
        <% @items.each do |item| %>
          <% item.assets.each do |asset| %>

            <% if temp_item!=item.title %>
              <li> <%= image_tag asset.url,:size => "138x152"   %>

                <h3><%= item.title   %></h3>
                <div><%= link_to  Store.find(item.store_id).organizationname , show_store_item_path(:id=>item.store_id )   %></div>
                <div class="cart_price"><%=  link_to "Show", show_item_path(:id => item.id) , :class => "adcart" %></div>
              </li>
              <% temp_item=item.title %>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="clear"></div>
  <div>&nbsp;</div>
</div>

app/views/stores/index.html.erb
<h3>Features Items</h3>

app/views/stores/new.html.erb
<%#= javascript_include_tag  "multifile" %>
<div class="main_wrap">
  <div style="padding: 10px 0 0 50px;">
    <% form_tag users_path, :multipart => true  do %>

      <table>
        <tr>
          <td> Login </td>
          <td> <%= text_field :user, :login %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Email' %></td>
          <td> <%= text_field :user, :email %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Password' %></td>
          <td> <%= password_field :user, :password %></td>
        </tr>

        <tr>
          <td>  Password <br/>Confirmation</td>
          <td> <%= password_field :user, :password_confirmation %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Firstname' %></td>
          <td> <%= text_field :store, :firstname %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Lastname' %></td>
          <td> <%= text_field :store, :lastname %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'OrganizationName' %></td>
          <td> <%= text_field :store, :organizationname %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Address1' %></td>
          <td> <%= text_field :store, :address1 %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Address2' %></td>
          <td> <%= text_field :store, :address2 %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'City' %></td>
          <td> <%= text_field :store, :city %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'State' %></td>
          <td> <%= text_field :store, :state %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Zip' %></td>
          <td> <%= text_field :store, :zip %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Phone' %></td>
          <td> <%= text_field :store, :phone %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Sport' %></td>
          <td> <%= text_field :store, :sport %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Established In' %></td>
          <td> <%= text_field :store, :established_in %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'GearDesignedBy' %></td>
          <td> <%= text_field :store, :geardesignedby %></td>
        </tr>
        <tr>
          <td> <%= label_tag 'Cause' %></td>
          <td> <%= text_field :store, :cause %><%= hidden_field :user, :user_type , :value => "STORE" %></td>

        </tr>
        <tr>
          <td> <%= label_tag 'Charity Or Club' %></td>
          <td> <select name="store[store_type]">
              <option value="club" selected="selected">CLUB</option>
              <option value="charity" >CHARITY</option>
            </select></td>

        </tr>
      <tr>
          <td> <%= label_tag 'Logo' %></td>
          <td> <%= file_field :store, :avatar %></td>

        </tr>
      </table>
      <div>
        <div  class="create_new" ><%= submit_tag '', :class=>"create_img"  %></div>
      </div><br/>

    <% end %>
  </div>
</div>

app/views/stores/new_address.html.erb
<%= javascript_include_tag "validation" %>
<div class="clear">&nbsp;</div>
<div><%= error_messages_for "order" %></div>
<% form_tag paypal_path, :name => "shipingForm" do %>
  <div style="padding-left:200px;">
    <div class="FL text_box">First Name:</div>
    <div class="FL"><%= text_field :order, :first_name, :class => "text_area" %></div>
    <div class="clear">&nbsp;</div>
    <div class="FL text_box">Last Name:</div>
    <div class="FL"><%= text_field :order, :last_name, :class => "text_area" %></div>
    <div class="clear">&nbsp;</div>
    <div class="FL text_box">Email:</div>
    <div class="FL"><%= text_field :order, :email, :class => "text_area" %></div>
    <div class="clear">&nbsp;</div>
    <div class="FL text_box">Address1:</div>
    <div class="FL"><%= text_field :order, :address1, :class => "text_area" %></div>
    <div class="clear">&nbsp;</div>
    <div class="FL text_box">Address2:</div>
    <div class="FL"><%= text_field :order, :address2, :class => "text_area" %></div>
    <div class="clear">&nbsp;</div>
    <div class="FL text_box">City:</div>
    <div class="FL"><%= text_field :order, :city, :class => "text_area" %></div>
    <div class="clear">&nbsp;</div>
    <div class="FL text_box">Zip Code:</div>
    <div class="FL"><%= text_field :order, :zip_code, :class => "text_area" %></div>
    <div class="clear">&nbsp;</div>
    <div class="FL text_box">State:</div>
    <div class="FL"><select id="order_state" name="order[state]" size="1">
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>
        <option value="AZ">Arizona</option>
        <option value="AR">Arkansas</option>
        <option value="CA">California</option>
        <option value="CO">Colorado</option>
        <option value="CT">Connecticut</option>
        <option value="DE">Delaware</option>
        <option value="DC">Dist of Columbia</option>
        <option value="FL">Florida</option>
        <option value="GA">Georgia</option>
        <option value="HI">Hawaii</option>
        <option value="ID">Idaho</option>
        <option value="IL">Illinois</option>
        <option value="IN">Indiana</option>
        <option value="IA">Iowa</option>
        <option value="KS">Kansas</option>
        <option value="KY">Kentucky</option>
        <option value="LA">Louisiana</option>
        <option value="ME">Maine</option>
        <option value="MD">Maryland</option>
        <option value="MA">Massachusetts</option>
        <option value="MI">Michigan</option>
        <option value="MN">Minnesota</option>
        <option value="MS">Mississippi</option>
        <option value="MO">Missouri</option>
        <option value="MT">Montana</option>
        <option value="NE">Nebraska</option>
        <option value="NV">Nevada</option>
        <option value="NH">New Hampshire</option>
        <option value="NJ">New Jersey</option>
        <option value="NM">New Mexico</option>
        <option value="NY">New York</option>
        <option value="NC">North Carolina</option>
        <option value="ND">North Dakota</option>
        <option value="OH">Ohio</option>
        <option value="OK">Oklahoma</option>
        <option value="OR">Oregon</option>
        <option value="PA">Pennsylvania</option>
        <option value="RI">Rhode Island</option>
        <option value="SC">South Carolina</option>
        <option value="SD">South Dakota</option>
        <option value="TN">Tennessee</option>
        <option value="TX">Texas</option>
        <option value="UT">Utah</option>
        <option value="VT">Vermont</option>
        <option value="VA">Virginia</option>
        <option value="WA">Washington</option>
        <option value="WV">West Virginia</option>
        <option value="WI">Wisconsin</option>
        <option value="WY">Wyoming</option>
      </select></div>
    <div class="clear">&nbsp;</div>  
    <div style="padding-left:200px;"><%= image_submit_tag("../images/submit_but.png", :onclick => "return form_validation();") %></div>
    <div class="clear">&nbsp;</div>
    <div class="clear">&nbsp;</div>
  </div>
<% end %>
<script type="text/javascript">
  var order_first_name = new LiveValidation('order_first_name');
  order_first_name.add(Validate.Presence);
  var order_last_name = new LiveValidation('order_last_name');
  order_last_name.add(Validate.Presence);
  var order_email = new LiveValidation('order_email');
  order_email.add(Validate.Presence);
  order_email.add(Validate.Email);
  function form_validation(){
    var order_address1 = new LiveValidation('order_address1');
    var order_city = new LiveValidation('order_city');
    var order_zip_code = new LiveValidation('order_zip_code');
    var order_state = new LiveValidation('order_state');
    if(document.getElementById("order_shipping_yes").checked){
      order_address1.add(Validate.Presence);
      order_city.add(Validate.Presence);
      order_zip_code.add(Validate.Presence);
      order_state.add(Validate.Presence);
    }
    else{
      order_address1.remove(Validate.Presence);
      order_city.remove(Validate.Presence);
      order_zip_code.remove(Validate.Presence);
      order_state.remove(Validate.Presence);
      if(order_first_name.validate() && order_last_name.validate() && order_email.validate()){document.shipingForm.submit();}
      else{return false;}
    }
  }
</script>

app/views/stores/payment_error.html.erb
<div>&nbsp;</div>
<div>&nbsp;</div>
<div style="padding-left:50px; color:#652803;">
<h2>Oops</h2>
<p>There was a problem with your PayPal order.  Please contact the administrator for assistance.</p>
</div>

app/views/stores/payment_success.html.erb
<div>&nbsp;</div>
<div>&nbsp;</div>
<div style="padding-left:50px; color:#652803;">
<div><h2>PayPal Success!</h2></div>
<p>Thank you for your payment. Your transaction has been completed, and a receipt for your purchase has been emailed to you. You may log into your account at <a href="http://www.paypal.com">http://www.paypal.com</a> to view details of this transaction.</p>
</div>

app/views/stores/show_cart.html.erb
<div style="padding-left: 700px;"><%= link_to " Continue Shopping", root_path  %>&nbsp;&nbsp;&nbsp&nbsp;&nbsp;<%= link_to " Checkout" , new_address_path  %>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to " Empty Cart" , empty_cart_path , :confirm=>"Are you want to empty the your cart?" %></div>
<div>&nbsp;</div>
<div style="padding:0 50px 0 50px;">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr style="color: #000000; font-size:14px;">
      <td style="padding:4px 8px 4px 8px;text-align:center;">Item Name</td>
      <td style="padding:4px 8px 4px 8px;text-align:center;">Quantity</td>
      <td style="padding:4px 8px 4px 8px;text-align:center;">Price</td>
      <td style="padding:4px 8px 4px 8px;text-align:center;">Total Price</td>
      <td style="padding:4px 8px 4px 50px;"colspan="2">Action</td>
    </tr>
    <% if !@cart.blank? %>
      <% $sum = 0 %>
      <% @cart.each do |a| %>
        <% item = Item.find_by_id(a[:item_id].to_i) %>
        <tr style="color: #652803; font-size:14px;">
          <% if a[:quantity] %>
            <td style="text-align:center;"><%= item.title %></td>
            <% form_tag update_cart_path  do %>
              <td style="text-align:center;"><%= text_field :cart , :quantity , :value => a[:quantity] , :size => 3 %>
                <%= hidden_field :cart , :id , :value => item.id %>
              </td>   
              <td style="text-align:center;">$<%= item.price %></td>
              <td style="text-align:center;">$<%= $total = a[:quantity].to_i * item.price.to_f %></td>
              <% $sum = $sum.to_f + $total.to_f %> 
              
               
              <td width="20px"><div class="remove_cart_img"><%= link_to image_tag("im_03.png"),remove_cart_path(:id =>item.id), :confirm=>"Are you sure?" %></div></td>
              <%#*<td style="text-align:center;"><%= link_to "Remove",remove_cart_path(:id =>item.id), :confirm=>"Are you sure?" %>
              <td><div  class="update_cart"  style="margin:0;"><%= submit_tag '', :class=>"update_cart_img"  %></div></td>
            
            <% end %>
          <% end %>
        </tr>
      <%end%>
      <tr style="color: #652803; font-size:14px;">
       
      </tr>
    <%end%>
  </table>

  <div>&nbsp;</div>
</div>

app/views/stores/show_item.html.erb
<div class="main_wrap">
  <div class="FL" style="width:235px;">Category</div>
  <div class="FL" style="width:765px;">
    <div class="FL" style="width: 300px;">
      <% if logged_in? %>
        <% if Store.find(@item.store_id).user_id.to_i== current_user.id.to_i %>
          <div class="tn3gallery">
            <%= flash[notice] %>

            <% item_hash = "item_#{@item.id}".to_sym %>
    <%#= render :partial => "attachment", :collection => @item.assets %>
            <% @item.assets.each do |asset| %>


              <a href='<%=asset.url %>'> <%= image_tag (asset.url,:size => "150x160")  %></a>


            <% end %>
          </div>
        </div>
        <div class="FL" style="width:400px; padding-left: 10px;">
          <b>Name:</b>
          <%= @item.title %>
          <p>
            <b>Description:</b>
            <%= @item.description %>
          </p>
          <p>
            <b>Price:</b>
            <%= @item.price %>
          </p>
          <p>
            <b>Size:</b>
            <%= @item.size %>
          </p>
          <p>
            <b>Club/Charity:</b>
            <%= Store.find(@item.store_id).organizationname %>
          </p>
          <p>
            <%= hidden_field item_hash , :item_id , :value => @item.id %>
          </p>
          <br/>
          <div class="edit_new_img"><%= link_to image_tag("im_07.png"),edit_item_path(@item) %></div>
          <%#= link_to "Edit",edit_item_path(@item) %>
        <% else %>
          <% form_tag add_to_cart_path(:item_id => @item.id) do %>

            <div class="tn3gallery">
              <%= flash[notice] %>

              <% item_hash = "item_#{@item.id}".to_sym %>
      <%#= render :partial => "attachment", :collection => @item.assets %>
              <% @item.assets.each do |asset| %>


                <a href='<%=asset.url %>'> <%= image_tag (asset.url,:size => "150x160")  %></a>


              <% end %>
            </div>
          </div>
          <div class="FL" style="width:400px; padding-left: 10px;">
            <b>Name:</b>
            <%= @item.title %>
            <p>
              <b>Description:</b>
              <%= @item.description %>
            </p>
            <p>
              <b>Price:</b>
              <%= @item.price %>
            </p>
            <p>
              <b>Size:</b>
              <%= @item.size %>
            </p>
            <p>
              <b>Club/Charity:</b>
              <%= Store.find(@item.store_id).organizationname %>
            </p>
            <p>
              <b>Quantity:</b>
              <%= text_field item_hash , :quantity , :value=>1 ,:size => 3 %>
            </p>
            <p>

              <%= hidden_field item_hash , :item_id , :value => @item.id %>
            </p>
            <br/>
            <div  class="add_to_cart" ><%= submit_tag "", :class=>"add_to_cart_img"  %></div>
            <%#= submit_tag "add to cart" %>
          <% end %>
        <% end %>
      <% else %>
        <% form_tag add_to_cart_path(:item_id => @item.id) do %>

          <div class="tn3gallery">
            <%= flash[notice] %>

            <% item_hash = "item_#{@item.id}".to_sym %>
    <%#= render :partial => "attachment", :collection => @item.assets %>
            <% @item.assets.each do |asset| %>


              <a href='<%=asset.url %>'> <%= image_tag (asset.url,:size => "150x160")  %></a>


            <% end %>
          </div>
        </div>
        <div class="FL" style="width:400px; padding-left: 10px;">
          <b>Name:</b>
          <%= @item.title %>
          <p>
            <b>Description:</b>
            <%= @item.description %>
          </p>
          <p>
            <b>Price:</b>
            <%= @item.price %>
          </p>
          <p>
            <b>Size:</b>
            <%= @item.size %>
          </p>
          <p>
            <b>Club/Charity:</b>
            <%= Store.find(@item.store_id).organizationname %>
          </p>
          <p>
            <b>Quantity:</b>
            <%= text_field item_hash , :quantity , :value=>1 ,:size => 3 %>
          </p>
          <p>

            <%= hidden_field item_hash , :item_id , :value => @item.id %>
          </p>
          <br/>
           <div  class="add_to_cart" ><%= submit_tag '', :class=>"add_to_cart_img"  %></div>
    <%#= submit_tag "add to cart" %>
        <% end %>
      <% end %>


    </div>
    <div class="clear">&nbsp;</div>
    <div style="padding-left: 25px;font-size: 20px;color: #FF0000;">Other Product From <%= Store.find(@item.store_id).organizationname %> </div>
    <div class="clear">&nbsp;</div>
    <div class="FL" style="width:765px;">
      <div class="listing">
        <ul>
          <%= temp_item="" %>
          <% @temp_items=Item.find(:all , :conditions => ["store_id =?",@item.store_id]) %>
          <% @temp_items.each do |item| %>
            <% if @item.title!=item.title %>
              <% item.assets.each do |asset| %>
                <% if temp_item!=item.title %>
                  <li> <%= image_tag (asset.url,:size => "138x152")  %>
                    <h3><%= item.title   %></h3>
                    <div id="blue"><%= item.description   %></div>
                    <div class="cart_price"><%=  link_to "Show", show_item_path(:id => item.id) , :class => "adcart" %></div>
                  </li>
                  <% temp_item=item.title %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/stores/show_store_item.html.erb
<div class="main_wrap">
  <div class="FL" style="width:235px;">Category</div>
  <div class="FL" style="width:765px;">
    <div class="FL" style="width: 200px;padding-left: 20px;">
      <%= image_tag Store.find(:first, :conditions => ["user_id=?",@store.user_id]).avatar.url(:thumb) %>
    </div>
    <div class="FL" style="width:400px;">
      <p >
        <b>Organisation Name:</b>
      <%= @store.organizationname %>
      </p>
      <p>
        <b>First Name:</b>
      <%= @store.firstname %>
      </p>
      <p>
        <b>Last Name:</b>
      <%= @store.lastname %>
      </p>
      <p>
        <b>Address:</b>
      <%= @store.address1 %> &nbsp;&nbsp;<%= @store.address2 %>
      </p>
      <p>
        <b>Sport:</b>
      <%= @store.sport %>
      </p>
    </div>
    <div class="clear">&nbsp;</div>
    <div style="padding-left: 25px;font-size: 20px;color: #FF0000;">List of Products From <%= @store.organizationname %> </div>
    <div class="clear">&nbsp;</div>
    <div class="FL" style="width: 765px;">
      <div class="listing">
        <ul>
        <%= temp_item="" %>
        <% @items.each do |item| %>
          <% item.assets.each do |asset| %>
            <% if temp_item!=item.title %>
              <li > <%= image_tag (asset.url,:size => "138x152")  %>
                <h3><%= item.title   %></h3>
                <div><%= link_to  Store.find(item.store_id).organizationname , show_store_item_path(:id=>item.store_id )   %></div>
                <div class="cart_price"><%=  link_to "Show", show_item_path(:id => item.id) , :class => "adcart" %></div>
              </li>
              <% temp_item=item.title %>
            <% end %>
          <% end %>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="clear"></div>


</div>