config/routes.rb
Mystore::Application.routes.draw do
  resources :users
  resources :stores
  resources :items
  resources :assets
  
  root :to => "stores#home"

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match '/admin' => 'admins#index', :as => :admin_index

  match '/admin/active' => 'admins#active', :as => :active

  match '/admin/inactive' => 'admins#inactive', :as => :inactive

  match 'show-item' => "stores#show_item" , :as => :show_item
  
  match 'show-store-item' => "stores#show_store_item" , :as => :show_store_item

  match 'add_to_cart' =>'stores#add_to_cart' , :as => :add_to_cart

  match 'show-cart' => 'stores#show_cart' , :as => :show_cart

  match 'remove-item/:id' =>'stores#remove_cart' , :as => :remove_cart

  match 'empty-cart' =>'stores#empty_cart' , :as => :empty_cart

  match 'update-cart' => 'stores#update_cart' , :as => :update_cart

  match 'new-address' =>'stores#new_address' , :as => :new_address

  match 'paypal'   =>'stores#paypal' ,:as => :paypal

  match 'indexpaypal'   =>'stores#indexpaypal' ,:as => :indexpaypal

  match 'payment-status' => 'stores#payment_status' , :as => :payment_status

  match 'payment-success' => 'stores#payment_success' , :as => :payment_success

  match 'payment-error' => 'stores#payment_error' , :as => :payment_error

  match 'all-charity' => 'stores#all_charity' , :as => :all_charity

  match 'all-club' => 'stores#all_club' , :as => :all_club

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :assets, :as => :attachable, :dependent => :destroy
	validate :validate_attachments
  has_many :lineitems

  Max_Attachments = 4
  Max_Attachment_Size = 1.megabyte

  def validate_attachments
    errors.add_to_base("Too many attachments - maximum is #{Max_Attachments}") if assets.length > Max_Attachments
    #assets.each {|a| errors.add_to_base("#{a.name} is over #{Max_Attachment_Size/1.megabyte}MB") if a.file_size > Max_Attachment_Size}
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def new
    @item=Item.new
  end
  def index
    @items=Item.all
  end

  def show
    @item=Item.find(params[:id])
  end

  def create
    @store=Store.find(:first, :conditions => ["user_id =?", current_user.id])
    @item = Item.new(params[:item])
    @item.store_id = @store.id
   
    respond_to do |format|
      if @item.save
        params[:attachment].each{|file|
          @item.assets.create(:data => file[1])
        } unless params[:attachment].blank?
        format.html { redirect_to(items_path, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end
  def edit
    @item =Item.find(params[:id])
  end

  def update
    @item =Item.find(params[:id])
    if @item.update_attributes(params[:item])
      redirect_to items_path
    else
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path

  end

  protected

  def process_file_uploads(item)
    i = 0
    while params['file_'+i.to_s] != "" && !params['file_'+i.to_s].nil?
      item.assets.create(:data => params['file_'+i.to_s])
      i += 1
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_attachment.html.erb
<% if !attachment.id.nil? %><li id='attachment_<%=attachment.id %>'> <%= image_tag (attachment.url,:size => "50x25")  %><a href='<%=attachment.url %>'><%=attachment.name %></a> (<%=attachment.file_size/1.kilobyte %>KB)
<%= link_to "Remove", asset_path(:id => attachment), :method => :delete, :confirm=>"Are You Sure" , :html => { :title  => "Remove this attachment", :id => "remove" } %></li>
<% end %>

app/views/items/_form.html.erb
<%= javascript_include_tag  "multifile" %>

<% form_for(@item, :url => items_path, :html => { :multipart => true } ) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :shippingprice %><br />
    <%= f.text_field :shippingprice %>
  </div>
  <div>Pending Attachments: (Max of <%= Item::Max_Attachments %>)
    <% if @item.assets.count >= Item::Max_Attachments %>
      <input id="newfile_data" type="file" disabled />
    <% else %>
      <input id="newfile_data" type="file" />

    <%#= file_field :attachment ,:data , :id=>"newfile_data"  %>
    <% end %>
    <div id="attachment_list"><ul id="pending_files"></ul></div>
    <script type="text/javascript">
      var multi_selector = new MultiSelector($('pending_files'), 4);
      multi_selector.addElement($('newfile_data'));
    </script>

  </div>


  <div class="actions">
    <div  class="create_new_item" ><%= f.submit '', :class=>"create_new_item_img" %></div>

  </div>
<% end %>

app/views/items/edit.html.erb
<div class="main_wrap">
  <div style="padding-left: 50px;">
    <h1>Editing item's detail</h1>

    <%= javascript_include_tag  "multifile" %>

    <% form_for(@item,:url => item_path, :html => { :multipart => true } ) do |f| %>
      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :Title %><br />
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :price %><br />
        <%= f.text_field :price %>
      </div>
      <div class="field">
        <%= f.label :quantity %><br />
        <%= f.text_field :quantity %>
      </div>
      <div class="field">
        <%= f.label :size %><br />
        <%= f.text_field :size %>
      </div>
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_field :description %>
      </div>
      <div class="field">
        <%= f.label :shippingprice %><br />
        <%= f.text_field :shippingprice %>
      </div>
      <div>Pending Attachments: (Max of <%= Item::Max_Attachments %>)
        <% if @item.assets.count >= Item::Max_Attachments %>
          <input id="newfile_data" type="file" disabled />
        <% else %>
          <input id="newfile_data" type="file" />

    <%#= file_field :attachment ,:data , :id=>"newfile_data"  %>
        <% end %>
        <div id="attachment_list"><ul id="pending_files"></ul></div>
        <script type="text/javascript">
          var multi_selector = new MultiSelector($('pending_files'), 4);
          multi_selector.addElement($('newfile_data'));
        </script>

      </div>


        <div  class="update_item" ><%= f.submit '', :class=>"update_item_img" %></div>
  <%#= f.submit "", :class=>"" %>

    <% end %>
  </div>

</div>

app/views/items/index.html.erb
<h1>Listing Items</h1>
<div style="padding-left: 50px;">
  <table border ="1" >
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3" align="center">Actions</th>
    </tr>

    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.price %></td>
        <td><%= link_to "show" , item  %></td>
        <td><%= link_to "update" , edit_item_path(item)  %></td>
        <td><%= link_to "Destroy", item, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>
</div>
<br />

app/views/items/new.html.erb
<div class="main_wrap">
  <div style="padding-left: 50px;">
    <h1>New Item</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/items/show.html.erb
<div class="main_wrap">
  <div style="padding-left: 50px;">
    <p id="notice"><%= notice %></p>
    <p>
      <b>Title:</b>
      <%=  @item.title %>
    </p>

    <p>
      <b>price:</b>
      <%=  @item.price %>
    </p>
    <p>
      <b>quantity:</b>
      <%=  @item.quantity %>
    </p>
    <p>
      <b>size:</b>
      <%=  @item.size %>
    </p>
    <p>
      <b>description:</b>
      <%=  @item.description %>
    </p>
    <p>
      <b>shipping price:</b>
      <%=  @item.shippingprice %>
    </p>
    <p><b>Attached Files:</b><div id="attachment_list"><%= render :partial => "attachment", :collection => @item.assets %></div></p>
<%#= link_to 'Back', items_path %>
  </div>
</div>