config/routes.rb
Mystore::Application.routes.draw do
  resources :users
  resources :stores
  resources :items
  resources :assets
  
  root :to => "stores#home"

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match '/admin' => 'admins#index', :as => :admin_index

  match '/admin/active' => 'admins#active', :as => :active

  match '/admin/inactive' => 'admins#inactive', :as => :inactive

  match 'show-item' => "stores#show_item" , :as => :show_item
  
  match 'show-store-item' => "stores#show_store_item" , :as => :show_store_item

  match 'add_to_cart' =>'stores#add_to_cart' , :as => :add_to_cart

  match 'show-cart' => 'stores#show_cart' , :as => :show_cart

  match 'remove-item/:id' =>'stores#remove_cart' , :as => :remove_cart

  match 'empty-cart' =>'stores#empty_cart' , :as => :empty_cart

  match 'update-cart' => 'stores#update_cart' , :as => :update_cart

  match 'new-address' =>'stores#new_address' , :as => :new_address

  match 'paypal'   =>'stores#paypal' ,:as => :paypal

  match 'indexpaypal'   =>'stores#indexpaypal' ,:as => :indexpaypal

  match 'payment-status' => 'stores#payment_status' , :as => :payment_status

  match 'payment-success' => 'stores#payment_success' , :as => :payment_success

  match 'payment-error' => 'stores#payment_error' , :as => :payment_error

  match 'all-charity' => 'stores#all_charity' , :as => :all_charity

  match 'all-club' => 'stores#all_club' , :as => :all_club

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
     <% if !current_user.blank? %>
    
  <% end if %>
  <title>Mystore</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="inned_boby">
<div class="main_wrap">
<div class="top_nav">
<ul>
<li><a href="#">About Us</a>|</li>
<li><a href="#">Contact</a>| </li>
<li><a href="#">Help</a></li>
</ul>
</div>
<div class="clear"></div>
<div class="logo"><img src="../images/logo.png" width="309" height="95" /></div>
<div class="nav_bg">

<div class="nab">
<ul>
<li><%= link_to 'Home', admin_index_path%></li>

<li><%= link_to 'Logout', logout_path %></li>
<li><a href="#"></a></li>
</ul>
</div>
</div>
<div class="body_border">
<div style="padding:20px 0 0 30px;">
<div><h2>ADMIN</h2></div>
<div style=" border-bottom:1px solid #999; margin:4px 20px 0 0"></div>
<p>&nbsp;</p>
<div class="admin_bg">

<div class=" admin_right">
<h3>Listing the details of all stores</h3>
<div style="height:10px;"></div>
<table border="3" align="center">

  <tr>
    <th>Organizationname</th>
    <th>Established In</th>
    <th>Cause</th>
    <th colspan="2" align="center">Actions</th>
  </tr>
  <% for store in @stores %>

    <tr>
      <td><%= store.organizationname %></td>
      <td><%= store.established_in %></td>
      <td><%= store.cause %></td>
      <% if User.find(store.user_id).status==true %>
        <td><%= link_to "Inactive", inactive_path(:id=>store.user_id) %></td>
        <% else %>
      <td><%= link_to "Active", active_path(:id=>store.user_id) %></td>
    <% end %>
   </tr>
  <% end %>
</table>

<br />


<%#= link_to 'Home', root_path %>
</div>

</div>
<p>&nbsp;</p>


<p>&nbsp;</p>
</div>
</div>

</div>

<%= yield %>
<div class="footer ">
<div class="main_wrap">
<div class="FL" style="padding:20px 0 0 20px;"><img src="../images/logo.png" width="309" height="95" /></div>
<div class=" FL top_nav" style="padding:40px 0 0 100px;">
<ul>
<li><a href="#">About Us</a>|</li>
<li><a href="#">Contact</a>| </li>
<li><a href="#">Help</a></li>
</ul>
</div>
<div class="clear"></div>
<p>&nbsp;</p>
</div>
</div>
</div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Mystore</title>
    <%= stylesheet_link_tag 'style','tn3' %>
    <%= javascript_include_tag 'application','controls','dragdrop','effects','jquery-1.6.4','jquery.tn3lite.min','prototype','rails','validation','magicthumb' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="inned_boby">
      <div class="main_wrap">
        <div class="top_nav">
          <ul>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
          </ul>
        </div>
        <div class="clear"></div>
        <div class="logo"><img src="../images/logo.png" width="309" height="95" /></div>
        <div class="nav_bg">
          <div class="nab">
            <ul>
              <li><%= link_to 'Home', root_path %></li>
              <% if !current_user.blank? %>
                <% if current_user.user_type=="STORE" && current_user.login!="admin" && current_user.status==true %>
                  <li><%= link_to "Add Item" , new_item_path   %></li>
                <% end %>
              <% end %>
              <% if !current_user.blank? %>
                <li> <%= link_to 'Logout', logout_path %></li>
              <% else %>
                <li><%= link_to "Login" , login_path   %></li>
              <% end %>
              <%#*<li><a href="#">Register</a></li>%>
              <li><%= link_to "Create Charity Or Club" , new_store_path   %></li>

            </ul>
          </div>
    
        </div>
              
</div>
        <%= yield %>
        <div class="footer ">
          <div class="main_wrap">
            <div class="FL" style="padding:20px 0 0 20px;"><img src="../images/logo.png" width="309" height="95" /></div>
            <div class=" FL top_nav" style="padding:40px 0 0 100px;">
             <!-- <ul>
                <li><a href="#">About Us</a>|</li>
                <li><a href="#">Contact</a>| </li>
                <li><a href="#">Help</a></li>
              </ul>-->
            </div>
            <div class="clear"></div>
            <p>&nbsp;</p>
          </div>
        </div>
      
    </div>
  </body>
</html>